<h1>Liste des articles</h1>
<?php if (Service::checkIfUserIsConnected()) { ?>
	<div class="d-flex justify-content-end mb-3">
		<a class="btn btn-warning" href="/?page=article_add">Créer un article</a>
	</div>
<?php }  ?>

<table class="table table-info table-striped">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">id</th>
			<th scope="col">Titre</th>
			<th scope="col">date de publication</th>
			<th scope="col">Action</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($params["articles"] as $key => $article) { ?>
			<tr>
				<th></th>
				<td><?php echo $article->getId() ?></td>
				<td><?php echo $article->getTitle() ?></td>
				<td><?php echo ($article->getDate_published())->format("d/m/Y") ?></td>
				<td>
					<a class="btn btn-primary" href="/?page=article_show&id=<?php echo $article->getId() ?>">Voir</a>
					<?php if (Service::checkIfUserIsConnected()) { ?>
						<button type="button" 
							class="btn btn-danger js_article_button_deleted" 
							data-bs-toggle="modal" 
							data-bs-target="#exampleModal" 
							data-article_id="<?php echo $article->getId() ?>"
						>
							Supprimer
						</button>
					<?php }  ?>
				</td>
			</tr>
		<?php } ?>
	</tbody>
</table>


<?php include_once dirname(__DIR__) . "/article/template_part/__deleted_modal.phtml"; ?>