<form action="" method="post">
    <div class="mb-3">
        <label for="lastname" class="form-label">Nom</label>
        <input type="text" class="form-control" id="lastname" name="lastname" placeholder="votre nom...">
    </div>
    <div class="mb-3">
        <label for="firstname" class="form-label">Prénom</label>
        <input type="text" class="form-control" id="firstname" name="firstname" placeholder="votre prénom...">
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">Nom d'utilisateur</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="votre nom  d'utilisateur...">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Mot de pass</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="votre not de passe...">
    </div>
    <input class="btn btn-warning" type="submit" value="Créer">
</form>

<div class="mt-3">
    <?php if (isset($params["error"]) && !empty($params)) { ?>
        <?php if (!$params["error"]) { ?>
            <div class="alert alert-danger" role="alert">
                <?php echo $params["message"] ?>
            </div>
        <?php } ?>
        <?php if ($params["error"]) { ?>
            <div class="alert alert-success" role="alert">
                <?php echo $params["message"] ?>
            </div>
        <?php } ?>
    <?php } ?>
</div>