<form action="" method="post">
    <div class="mb-3">
        <label for="username" class="form-label">Nom d'utilisateur</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="votre nom  d'utilisateur...">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Mot de pass</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="votre not de passe...">
    </div>
    <input class="btn btn-warning" type="submit" value="Créer">

</form>