<form action="" method="post">
    <div class="mb-3">
        <label for="username" class="form-label">Nom d'utilisateur</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="votre nom  d'utilisateur...">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Mot de pass</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="votre not de passe...">
    </div>
    <input class="btn btn-warning" type="submit" value="Créer">
</form>

<div class="mt-3">
    <?php if (isset($params["error"]) && !empty($params)) { ?>
        <?php if (!$params["error"]) { ?>
            <div class="alert alert-danger" role="alert">
                Erreur: l'utilisateur ou le mot de passe ne sont pas valide.
            </div>
        <?php } ?>
        <?php if ($params["error"]) { ?>
            <div class="alert alert-success" role="alert">
                Vous étes connecté.
            </div>
        <?php } ?>
    <?php } ?>
</div>